In [2]:
print("Hi")

Hi


In [3]:
n = int(input())
li = []
for i in range(n):
    li.append(int(input()))
for i in range(n):
   
    if i == n-1 :
        print(li[i],end="")
       
    else:
        print(li[i],end=" ")

 4
 1
 2
 3
 4


1 2 3 4

In [4]:
li = list(map(int,input().split()))
n = int(input())
print(li.count(n))

 1 2 3 4 5
 4


1


In [5]:
li = list(map(int,input().split()))
li[::-1]

 3 5 6 7


[7, 6, 5, 3]

In [7]:

n = int(input())
for i in range(n+1):
    for j in range(n+1):
        if i==0 or i==n:
            print("*",end=" ")
        elif j==0 or j == n:
            print("*",end=" ")
        else:
            print(" ",end=" ")
    print()

 10


* * * * * * * * * * * 
*                   * 
*                   * 
*                   * 
*                   * 
*                   * 
*                   * 
*                   * 
*                   * 
*                   * 
* * * * * * * * * * * 


In [8]:
import matplotlib.pyplot as ply
import seaborn
import pandas as pd
import numpy as np


In [13]:
arr=np.array([1,2,3,4])
arr1=np.array([5,6,7,8])
print(arr+arr1)
print(arr-arr1)
print(arr*arr1)
print(arr/arr1)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [5]:
li=[1,2,3]
print(type(li))

<class 'list'>


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
print(arr.ndim)

1


In [8]:
print(arr.size)

4


In [9]:
arr.dtype

dtype('int32')

In [10]:
arr.itemsize

4

In [11]:
print(arr.size*arr.itemsize)

16


In [14]:
print(np.sum([arr,arr1]))

36


In [15]:
print(np.multiply(arr,arr1))

[ 5 12 21 32]


In [16]:
print(np.divide(arr,arr1))

[0.2        0.33333333 0.42857143 0.5       ]


In [17]:
print(np.power(arr,arr1))

[    1    64  2187 65536]


In [18]:
print(np.mod(arr,arr1))

[1 2 3 4]


In [19]:
arr.shape

(4,)

In [20]:
arr.reshape(4,)

array([1, 2, 3, 4])

In [21]:
arr.shape[0]

4

In [24]:
print(arr1[0:2])

[5 6]


In [27]:
from numpy import random
val=random.randint(low=11,high=20)
print(val)

11


In [28]:
val2=random.choice([1,2,3,4,5])
print(val2)

4


In [31]:
newarr1=np.arange(10,20,2)
print(newarr1)

[10 12 14 16 18]


In [32]:
random.shuffle(arr1)
print(arr1)

[7 5 6 8]


In [33]:
arr2=[-1,-2,-3,-4,-5]++




































SyntaxError: invalid syntax (2740035591.py, line 1)

In [ ]:
import numpy as np
from numpy import random
num = int(input("ENTER VALUES FROM 0 - 100"))
count = 0
start = random.randint(1,90)
end = start + 10
print(start,end)
while(num > 0 ):
    count = count+1;
    ans = random.randint(start,end)
    print(ans)
    if(ans == num):
        print("congrats found on %d tries"%count)
       
        break;
    elif(ans >  num ):
        print("try greater num")
    else:
        print("try smaller num")
    num = int(input("ENTER VALUES FROM 0 - 100"))

ENTER VALUES FROM 0 - 100 1


37 47
44
try greater num


ENTER VALUES FROM 0 - 100 5


40
try greater num


ENTER VALUES FROM 0 - 100 2


40
try greater num


In [1]:
from numpy import random
def batting1(player1,player2):
    score1 = 0
    while True:
        print(player1,end=" ")
        val1 = random.randint(0,6)
        val2 = random.randint(0,6)
        print("kept %d and %s kept %d"%(val1,player2,val2))
        if val1==val2 :
            break
        score1+=val1;
       
    return int(score1)
def batting(player1,player2,score):
    score1 = 0
    while True:
        print(player1,end=" ")
        val1 = random.randint(0,6)
        val2 = random.randint(0,6)
        print("kept %d and %s kept %d"%(val1,player2,val2))
        if val1==val2 :
            break
        score1+=val1;
        if score1>score:
            return 10000000
       
       
    return int(score1)

player1_toss = int(input("Enter head(0) or tails(1) :"))
toss = random.randint(0,2)
if toss == player1_toss :
    choosing= int(input("You won toss choose batting(0) or bowling(1):"))
    if choosing==0:
        score = batting1("player1","player2")
        print("player 2 playing")
        score1 = batting("player2","player1",score)
        if(score > score1) :
            print("player 1 won")
        else :
            print("print 2 won")
    else:
        score = batting1("player2","player1")
        print("player 1 playing")
        score1 = batting("player1","player2",score)
        if(score > score1):
            print("player 2 won")
        else:
            print("player 1 won")
       
else:
    player2_choosing = random.randint(0,2)
    if player2_choosing == 0:
        score = batting1("player2","player1")
        print("player 1 playing")
        score1 = batting("player1","player2",score)
        if(score > score1):
            print("player 2 won")
        else:
            print("player 1 won")
    else:
        score = batting1("player1","player2")
        print("player 2 playing")
        score1 = batting("player2","player1",score)
        if(score > score1) :
            print("player 1 won")
        else :
            print("player 2 won")



           
           
       
       
   


Enter head(0) or tails(1) : 0


player2 kept 0 and player1 kept 0
player 1 playing
player1 kept 4 and player2 kept 1
player 1 won


In [9]:
import random

def super_over():
    
    team1 = "CSK"
    team2 = "MI"

    
    toss_result = random.choice(['H', 'T'])


    user_toss = input("Enter your toss choice (H/T): ").upper()

    
    if (toss_result == 'H' and user_toss == 'H') or (toss_result == 'T' and user_toss == 'T'):
        batting_team = team1
        print(f"{batting_team} wins the toss and will bat first.")
    else:
        batting_team = team2
        print(f"{batting_team} wins the toss and will bat first.")


    team1_score = team2_score = 0
    team1_wickets = team2_wickets = 0

    
    for _ in range(6):
        run = random.choice([0, 1, 2, 3, 4, 6, 'w'])

        if batting_team == team1:
            if run != 'w':
                team1_score += run
            else:
                team1_wickets += 1
        else:
            if run != 'w':
                team2_score += run
            else:
                team2_wickets += 1

        if team1_wickets == 2 or team2_wickets == 2:
            print(f"{batting_team} is all out!")
            break

    batting_team = team2 if batting_team == team1 else team1

 
    team1_wickets = team2_wickets = 0

    for _ in range(6):
        run = random.choice([0, 1, 2, 3, 4, 6, 'w'])

        if batting_team == team1:
            if run != 'w':
                team1_score += run
            else:
                team1_wickets += 1
        else:
            if run != 'w':
                team2_score += run
            else:
                team2_wickets += 1


        if team1_wickets == 2 or team2_wickets == 2:
            print(f"{batting_team} is all out!")
            break

    if team1_score > team2_score:
        print(f"{team1} WINS!!!")
    elif team2_score > team1_score:
        print(f"{team2} WINS!!!")
    else:
        print("DRAW!!!")

super_over()



Enter your toss choice (H/T):  5


MI wins the toss and will bat first.
MI WINS!!!


In [3]:
Dataset - > outside program it is known as Dataset
Data Frame - > inside program it is known as DataFrame

SyntaxError: invalid syntax (3617131169.py, line 1)

In [4]:
import pandas as pd
a = pd.read_csv("py.csv")
a

age  income vehicle
0   20   15000    alto
1   22   25000    alto
2   24   30000    alto
3   30   40000  baleno
4   32   60000  baleno
5   40  100000    audi
6   43  150000    audi
7   46  200000    audi

In [8]:
a.dropna(inplace=True)


In [9]:
a.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [10]:
import pandas as pd
a = pd.read_csv("assignmentreport_copy.csv")
a

Name RollNumber  MCQ 1 Score  \
0                        Bala Sweatha S D    20AD008         20.0   
1                               Pradeep K    20AD040         20.0   
2                                Raghul G    20CY019         18.0   
3                         Vishnupriya B E    20EC138         17.0   
4   Gummireddigari Kadireddi Vijaya Durga    20CS014         16.0   
..                                    ...        ...          ...   
60                              Deepika S    20MD002          5.0   
61                             Priyanka G        NaN          4.0   
62                               Vahini D    20CS170          3.0   
63                        Muthaiyanavendr    20EC081          NaN   
64                             Dhanasri A    20IT007          NaN   

    Coding Assessment 1  No.of Coding Question  Total Score  
0                  75.0                      2           95  
1                  75.0                      2           95  
2                  75.0                      2           93  
3                  75.0                      2           92  
4                  75.0                      2           91  
..                  ...                    ...          ...  
60                  NaN                      0            5  
61                  NaN                      0            4  
62                  0.0                      0            3  
63                  0.0                      0            0  
64                  0.0                      0            0  

[65 rows x 6 columns]

In [11]:
newdf = pd.read_csv("carvsbike.csv")
newdf
newdf['model'].value_counts()

model
bike    15
car     14
Name: count, dtype: int64

In [1]:
n = int(input())
x = int(input())
y = int (input())
z = int(input())
original = 0
first = 0
last = 0
for i in range(9,0,-1):
    for j in range (9,0,-1):
        ans = (i*10000)+(x*1000)+(y*100)+(z*10)+j
        if ans%n == 0:
            original = ans
            first = i
            last = j
print(original//72,first,last)

 72
 6
 7
 9


511 3 2


In [17]:
import pandas as pd
df = pd.read_csv("py.csv")

In [3]:
df

age  income vehicle
0   20   15000    alto
1   22   25000    alto
2   24   30000    alto
3   30   40000  baleno
4   32   60000  baleno
5   40  100000    audi
6   43  150000    audi
7   46  200000    audi

In [18]:
from sklearn.tree import DecisionTreeClassifier

In [19]:
x =df.drop(columns=['vehicle'])
y =df['vehicle']
x

age  income
0   20   15000
1   22   25000
2   24   30000
3   30   40000
4   32   60000
5   40  100000
6   43  150000
7   46  200000

In [20]:
model = DecisionTreeClassifier()

In [21]:
model.fit(x,y)

DecisionTreeClassifier()

In [22]:
import numpy as np
x = int(input())
y = int(input())
data_point = np.array([x, y]).reshape(1, -1)
ans = model.predict(data_point)
print(ans)


 40
 10000


['baleno']


C:\Users\91979\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [14]:
n = int(input())
x = list(map(int,input().split()))
original = 0
first = 0
last = 0
for i in range(9,0,-1):
    for j in range (9,0,-1):
        ans = (i*10000)+(x[0]*1000)+(x[1]*100)+(x[2]*10)+j
        if ans%n == 0:
            original = ans
            first = i
            last = j
print(first,last,original//n)

 72
 6 7 9


3 2 511


In [23]:
import numpy as np
from numpy import random
num = int(input("ENTER VALUES FROM 0 - 100"))
count = 0
start = random.randint(1,90)
#print(start,start + 10)
while(num >=0 ):
    count = count+1;
    ans = random.randint(start,start + 10)
    #print(ans)
    if(ans == num):
        print("congrats found on %d tries"%count)
        break;
    elif(ans >  num ):
        print("try greater num")
    else:
        print("try smaller num")
    num = int(input("ENTER VALUES FROM 0 - 100"))


ENTER VALUES FROM 0 - 100 2


try greater num


ENTER VALUES FROM 0 - 100 7


try greater num


ENTER VALUES FROM 0 - 100 8


try greater num


ENTER VALUES FROM 0 - 100 10


try greater num


ENTER VALUES FROM 0 - 100 55


try greater num


ENTER VALUES FROM 0 - 100 100


try smaller num


ENTER VALUES FROM 0 - 100 101


try smaller num


ENTER VALUES FROM 0 - 100 hhu


ValueError: invalid literal for int() with base 10: 'hhu'

In [25]:
count = 0
num = input()
length = len(num)
temp = int(num)
ans = 0

while(temp!=0):
   
    rem = temp%10
    set1 = set({})
    while(True):
        ran = random.randint(0,9)
        set1.add(ran)
       
        if(ran == rem):
            break
        count = count+1
    temp//=10

count

 467


18

In [14]:
import pandas as pd
df = pd.read_csv("fiat500.csv")
df

ID   model  engine_power  age_in_days      km  previous_owners  \
0        1  lounge            51          882   25000                1   
1        2     pop            51         1186   32500                1   
2        3   sport            74         4658  142228                1   
3        4  lounge            51         2739  160000                1   
4        5     pop            73         3074  106880                1   
...    ...     ...           ...          ...     ...              ...   
1533  1534   sport            51         3712  115280                1   
1534  1535  lounge            74         3835  112000                1   
1535  1536     pop            51         2223   60457                1   
1536  1537  lounge            51         2557   80750                1   
1537  1538     pop            51         1766   54276                1   

            lat        lon  price  
0     44.907242   8.611560   8900  
1     45.666359  12.241890   8800  
2     45.503300  11.417840   4200  
3     40.633171  17.634609   6000  
4     41.903221  12.495650   5700  
...         ...        ...    ...  
1533  45.069679   7.704920   5200  
1534  45.845692   8.666870   4600  
1535  45.481541   9.413480   7500  
1536  45.000702   7.682270   5990  
1537  40.323410  17.568270   7900  

[1538 rows x 9 columns]

In [15]:
df.isnull().sum()

ID                 0
model              0
engine_power       0
age_in_days        0
km                 0
previous_owners    0
lat                0
lon                0
price              0
dtype: int64

In [16]:
tempdf = df[['engine_power','age_in_days','km','previous_owners','price']]
tempdf

engine_power  age_in_days      km  previous_owners  price
0               51          882   25000                1   8900
1               51         1186   32500                1   8800
2               74         4658  142228                1   4200
3               51         2739  160000                1   6000
4               73         3074  106880                1   5700
...            ...          ...     ...              ...    ...
1533            51         3712  115280                1   5200
1534            74         3835  112000                1   4600
1535            51         2223   60457                1   7500
1536            51         2557   80750                1   5990
1537            51         1766   54276                1   7900

[1538 rows x 5 columns]

In [17]:
sports = df[df['model'] == 'sport']
sports

ID  model  engine_power  age_in_days      km  previous_owners  \
2        3  sport            74         4658  142228                1   
8        9  sport            73         4049   76000                1   
9       10  sport            51         3653   89000                1   
27      28  sport            51         3531  100000                1   
33      34  sport            51         3927  140000                2   
...    ...    ...           ...          ...     ...              ...   
1498  1499  sport            51         1400   60000                1   
1501  1502  sport            51         3774  161900                1   
1504  1505  sport            51         4322   95000                1   
1531  1532  sport            73         4505  127000                1   
1533  1534  sport            51         3712  115280                1   

            lat       lon  price  
2     45.503300  11.41784   4200  
8     45.548000  11.54947   5600  
9     45.438301  10.99170   6000  
27    40.976452  14.17228   4950  
33    40.755932  14.69019   5200  
...         ...       ...    ...  
1498  45.802021   9.18779  10800  
1501  44.906120   7.67723   4500  
1504  40.928501  14.20367   4500  
1531  45.528511   9.59323   4750  
1533  45.069679   7.70492   5200  

[86 rows x 9 columns]

In [18]:
sports.min()

ID                        3
model                 sport
engine_power             51
age_in_days             517
km                     6200
previous_owners           1
lat                38.11274
lon                 7.33099
price                  3800
dtype: object

In [19]:
tempdf.corr()

engine_power  age_in_days        km  previous_owners  \
engine_power         1.000000     0.319190  0.285495        -0.005030   
age_in_days          0.319190     1.000000  0.833890         0.075775   
km                   0.285495     0.833890  1.000000         0.097539   
previous_owners     -0.005030     0.075775  0.097539         1.000000   
price               -0.277235    -0.893328 -0.859373        -0.076274   

                    price  
engine_power    -0.277235  
age_in_days     -0.893328  
km              -0.859373  
previous_owners -0.076274  
price            1.000000

In [26]:
sports = df[df['model'] == 'sport']
pop = df[df['model'] == 'pop']
lounge = df[df['model'] == 'lounge']

In [27]:
print(sports['km'].max())
print(pop['km'].max())
print(lounge['km'].max())

190000
201000
235000


In [28]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
x = sports.drop(columns=['ID','engine_power','model','lat','lon','price'])
y = sports['price']
model.fit(x,y)
x1 = pop.drop(columns=['ID','engine_power','model','lat','lon','price'])
y1 = pop['price']
pop = LinearRegression()
pop.fit(x1,y1)
x2 = lounge.drop(columns=['ID','engine_power','model','lat','lon','price'])
y2 = lounge['price']
lounge = LinearRegression()
pop.fit(x2,y2)
import numpy as np
models = input()
ansli = []
number_of_cars = int(input())

if models == 'sports':
    for i in range(number_of_cars):
        x = int(input())
        y = int(input())
        z = int(input())
        data = np.array([x,y,z]).reshape(1,-1)
        ans = model.predict(data)
        ansli.append(ans)
elif models == 'pop':
    for i in range(number_of_cars):
        x = int(input())
        y = int(input())
        z = int(input())
        data = np.array([x,y,z]).reshape(1,-1)
        ans = pop.predict(data)
        ansli.append(ans)
elif models == 'lounge':
    for i in range(number_of_cars):
        x = int(input())
        y = int(input())
        z = int(input())
        data = np.array([x,y,z]).reshape(1,-1)
        ans = lounge.predict(data)
        ansli.append(ans)
       
for i in range(len(ansli)):
    print(ansli[i])


 jn
 hjj


ValueError: invalid literal for int() with base 10: 'hjj'

In [30]:

df = pd.get_dummies(df,dtype=int)
df = df.drop(columns=['ID','lat','lon'])


In [32]:
newdf = df
newdf

engine_power  age_in_days      km  previous_owners  price  model_lounge  \
0               51          882   25000                1   8900             1   
1               51         1186   32500                1   8800             0   
2               74         4658  142228                1   4200             0   
3               51         2739  160000                1   6000             1   
4               73         3074  106880                1   5700             0   
...            ...          ...     ...              ...    ...           ...   
1533            51         3712  115280                1   5200             0   
1534            74         3835  112000                1   4600             1   
1535            51         2223   60457                1   7500             0   
1536            51         2557   80750                1   5990             1   
1537            51         1766   54276                1   7900             0   

      model_pop  model_sport  
0             0            0  
1             1            0  
2             0            1  
3             0            0  
4             1            0  
...         ...          ...  
1533          0            1  
1534          0            0  
1535          1            0  
1536          0            0  
1537          1            0  

[1538 rows x 8 columns]

In [33]:
x3 = newdf.drop(columns=['price','engine_power'])
y3 = newdf['price']
new_model = LinearRegression()
new_model.fit(x3,y3)

LinearRegression()

In [34]:
ans = new_model.predict([[2190,70000,1,1,0,0]])
ans

C:\Users\91979\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([7880.66130631])

In [35]:
n = int(input("Enter no of cars"))
for i in range(n):
    x = int(input("Enter age in days"))
    y = int(input("Enter no of kms"))
    z = int(input("previous owners"))
    a = int(input("is it lounge"))
    b = int(input("is it pop"))
    c = int(input("is it sport"))
    ans = new_model.predict([[x,y,z,a,b,c]])
    print(ans)


Enter no of cars 2
Enter age in days 55
Enter no of kms 2555
previous owners 1
is it lounge 2
is it pop 2
is it sport 1


C:\Users\91979\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


[10756.20223099]


Enter age in days 10
Enter no of kms ki'


ValueError: invalid literal for int() with base 10: "ki'"

In [36]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x3,y3,test_size=0.33)
testmodel = LinearRegression()
testmodel.fit(X_train,y_train)
#ans = testmodel.predict(X_test)


LinearRegression()

In [37]:
sum1= testmodel.predict(X_test).sum()
sum1
sum2= y_test.sum()
accuracy = (sum2-sum1)/508
accuracy

-9.38836451700896

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [3]:
df = df.fillna(0)

In [4]:
df['experience']

0         0
1         0
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [5]:
df = df.replace({'five':5,'two':2,'seven':7,'three':3,'ten':10,'eleven':11})

In [6]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    0.0                           7      72000
7          11                    7.0                           8      80000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   experience                  8 non-null      int64  
 1   test_score(out of 10)       8 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64  
 3   salary($)                   8 non-null      int64  
dtypes: float64(1), int64(3)
memory usage: 388.0 bytes


In [11]:
from sklearn.linear_model import LinearRegression
x = df.drop(columns=['salary($)'])
y = df['salary($)']

In [9]:
x

experience  test_score(out of 10)  interview_score(out of 10)
0           0                    8.0                           9
1           0                    8.0                           6
2           5                    6.0                           7
3           2                   10.0                          10
4           7                    9.0                           6
5           3                    7.0                          10
6          10                    0.0                           7
7          11                    7.0                           8

In [10]:
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
model = LinearRegression()
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)
model.fit(X_train,y_train)

LinearRegression()

In [13]:
model.predict([[2,9,6]])

C:\Users\91979\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([52818.09385583])